### ISSUE TITLE
Empty repository & 'all' architecture packages

### ISSUE THREAD

**Issue by durana** [rcrowley/freight#1]
Looks like if you have an empty repository and you try to add a package with an architecture of 'all', freight-cache will fail.

```
root@host:/home/adurana# freight add freight_0.0.5-1_all.deb apt/lucid
root@host:/home/adurana# freight cache apt/lucid
eval: 1: cannot create /var/cache/freight/dists/lucid-20110504165444116189841/main/binary-apt/Release: Directory nonexistent
```

I suspect lib/freight/apt.sh:62 is the problem because there are no binary-\* directories to pick up a list of architectures from, but I'm not certain because I haven't had a whole lot of time to look at this.

**Comment by rcrowley** [comment]
Closed by b93673ac788af7bea4a31f9bc56dc4d42692752a.  Thanks!
