### ISSUE TITLE
freight-cache fails to generate cache with no such file or directory error

### ISSUE THREAD

**Issue by thereforsunrise** [rcrowley/freight#11]
Briefly, after adding a few packages and trying to run freight-cache, I get:

~  ᐅ sudo freight-cache -c /etc/freight.conf 
chmod: cannot access `/var/cache/freight/work.2745.tth3hpp4z4/gpg/keyring.gpg': No such file or directory

Tracking this down this seems to be due to:

223         chmod 644 "$TMP/gpg/keyring.gpg"
224         mv "$TMP/gpg/pubring.gpg" "$VARCACHE/keyring.gpg"

Are these lines the wrong way round?

**Comment by timurb** [comment]
Could you please regenerate the deb package at packages.devstructure.com as this fix is not pushed into that yet?
