### ISSUE TITLE
freight-cache seems to ignore gpg-agent

### ISSUE THREAD

**Issue by haus** [rcrowley/freight#14]
After calling keychain --eval and exporting the GPG_AGENT_INFO, calling freight-cache should ideally use the agent and not need to prompt for my passphrase. However, freight-cache is not using the agent, and will always prompt for the passphrase, unless the key is passphraseless. Output follows.

No GPG_AGENT_INFO to start...

``` shell
matthaus@host:~$ env
TERM=xterm
SHELL=/bin/bash
SSH_CLIENT=xx.xx.xx.xx 1413 22
SSH_TTY=/dev/pts/0
USER=matthaus
MAIL=/var/mail/matthaus
PATH=/usr/local/bin:/usr/bin:/bin:/usr/local/games:/usr/games
PWD=/home/matthaus
LANG=en_US.UTF-8
SHLVL=1
HOME=/home/matthaus
LOGNAME=matthaus
SSH_CONNECTION=xx.xx.xx.xx 1413 yy.yy.yy.yy 22
_=/usr/bin/env
```

Calling keychain to get the GPG_AGENT_INFO to export.

``` shell
matthaus@host:~$ keychain -q --agents gpg --eval <KEYID>
GPG_AGENT_INFO=/tmp/gpg-vZRZAA/S.gpg-agent:17921:1; export GPG_AGENT_INFO;

matthaus@host:~$ GPG_AGENT_INFO=/tmp/gpg-vZRZAA/S.gpg-agent:17921:1; export GPG_AGENT_INFO;
```

Env now has GPG_AGENT_INFO listed.

``` shell
matthaus@host:~$ env
GPG_AGENT_INFO=/tmp/gpg-vZRZAA/S.gpg-agent:17921:1
TERM=xterm
SHELL=/bin/bash
SSH_CLIENT=xx.xx.xx.xx 1413 22
SSH_TTY=/dev/pts/0
USER=matthaus
MAIL=/var/mail/matthaus
PATH=/usr/local/bin:/usr/bin:/bin:/usr/local/games:/usr/games
PWD=/home/matthaus
LANG=en_US.UTF-8
SHLVL=1
HOME=/home/matthaus
LOGNAME=matthaus
SSH_CONNECTION=xx.xx.xx.xx 1413 yy.yy.yy.yy 22
_=/usr/bin/env
```

Now I expect freight-cache to use the agent to get the key, but it doesn't.

``` shell
matthaus@host:~$ freight-cache apt/lenny

You need a passphrase to unlock the secret key for
user: "Key Description"
4096-bit RSA key, ID <KEYID>, created <CREATION DATE>

Enter passphrase: 
gpg: Interrupt caught ... exiting
```

**Comment by rcrowley** [comment]
Hi @haus,

I must admit my ignorance surrounding GPG and its agent.  I'm obviously able to reproduce the issue but don't know how to proceed.  I have my own `gpg-agent` running and `GPG_AGENT_INFO` is in the environment.  How do I add my `packages@rcrowley.org` key to the agent?

And now for the solution, which I was hoping to verify myself: it seems to be as simple as adding `--use-agent` to the `gpg` invocation in Freight.  Barring me being able to get the agent working, could you help verify that solution?

Thanks!

Richard

**Comment by haus** [comment]
Awesome! That totally works (added to apt.sh).

And I'm not very good with GPG myself, but this is my understanding of agent and getting keys into it.

And as long as your key is known to gpg, (gpg --import <KEYID>), running `eval $(gpg-agent --daemon)` should enable the agent to load the key whenever needed, after unlocking for the first use. Or, once gpg knows about it, running `eval $(keychain -q --agents gpg --eval <KEYID>)` should also make the key available for freight. To get the key id, run `gpg -K` and there should be a listing for each key, that looks something like

```
sec   4096R/KEYID Creation Date [expires: Expiration Date]
uid                  Key Description <packages.rcrowley.org>
```

4096R in this case is the key length and key algorithm.
