### ISSUE TITLE
Fix tag name for version 0.3.2

### ISSUE THREAD

**Issue by joschi** [rcrowley/freight#29]
The tag for version 0.3.2 contains a typo and is called "v0.32". Since the previous versions were called "v0.3.0" and "v0.3.1" I suppose this wasn't on purpose.

Please rename the tag to the correct version number. This would tremendously help when trying to package (no pun intended) freight for a Linux distribution.

**Comment by rcrowley** [comment]
How embarrassing!

Fixed.  Thank you.

**Comment by joschi** [comment]
Thanks! :)
