### ISSUE TITLE
Freight fix for non TTY conditions when run with set -e

### ISSUE THREAD

**Issue by sts** [rcrowley/freight#30]
I'm about to add Freight support to [jenkins-debian-glue](https://github.com/mika/jenkins-debian-glue/pull/40). A Framework for building Debian packages with Jenkins.

Jenkins-debian-glue uses `set -e`, in its scripts, which exits immediately  if a command exits with a nonzero status.

Your patch from #28, 4e4e678c3ad6509e26f73860368eeb472c094353 is evaluating the no-tty option for gpg in an incompatible way, because tty exits with a nonzero status.

Adding `|| true` to the evaluation fixes this behavior:

``` bash
TTY="$(tty -s && echo "1"|| true)"
```

**Comment by rcrowley** [comment]
So it does.  Thank you for the report, @sts.
