### ISSUE TITLE
Hard link from source during freight-add

### ISSUE THREAD

**Issue by gregswift** [rcrowley/freight#36]
Jenkins pushes our packages to our repository server.  Once it lands there freight-add is run to add it to our repository.  The way Jenkin is pushing it, we can't just delete the source package (it comes right back on next build).  Would be nice if freight-add would just hard-link if the source is on the same filesystem as the target.

**Comment by antaflos** [comment]
You can just have Jenkins push the packages to /var/lib/freight directly using rsync. It's what we do and I have yet to find a downside to that approach.

**Comment by gregswift** [comment]
Does require we change things a bit though.  The user can push files to the box, but it can't publish them to the repository.  That's managed by an incron initiated process.  Beneficial for making sure a compromised minimal access account can't seed the repository with data that hasn't been checked by another script.

**Comment by rcrowley** [comment]
Apologies for the delayed response, @gregswift.  I'm not entirely I understand the problem that hard-linking into `/var/lib/freight` would solve but I can say that hard-linking into `/var/lib/freight` would throw a monkey-wrench into Freight's internal reference counting for when to include a package in `Packages`.

**Comment by rackergs** [comment]
For us the solving would be not having duplicate files on the filesystem, however if its a non-starter because of Freight's internals then no worries.. we alleviated our problem in other ways.
