### ISSUE TITLE
Suite: $DIST should be configurable and default to "unstable"

### ISSUE THREAD

**Issue by 7ojo** [rcrowley/freight#43]
"Suite: " field on Release files should be configurable and be one of the specified: unstable, stable, oldstable, etc. Defined in https://wiki.debian.org/RepositoryFormat#A.22Release.22_files

lib/freight/apt.sh:156

(Suite: field affects on repository priority defined in /etc/apt/preferences)

**Comment by rcrowley** [comment]
Currently, `Suite` is configurable in `freight.conf` and defaults to the same value as `Codename`.  Does that give you what you need?

I don't feel a great need to implement Debian policy in its entirety but rather just to give people a solid and straightforward tool for distributing binary packages.

**Comment by 7ojo** [comment]
Yes, everything is ok now. Thanks :) I'm with you on that implementing debian policy enterily isn't feasible.
