### ISSUE TITLE
Handling of source packages is undocumented

### ISSUE THREAD

**Issue by Shnatsel** [rcrowley/freight#46]
All the Freight documentation I could find deals with binary .deb packages and doesn't mention source packages. 

They seem to be supported in some way - when I try to freight-add a .dsc is copies it over to the library, but freight-cache complains that it's an invalid source package. When I try to add .tar.gz containing the source code freight-add just prints usage.

Could you document how source packages should be handled in Freight so I could figure out what I'm doing wrong? I need to publish source code of the packages in the repository per GPL source code availability requirements.

**Comment by rcrowley** [comment]
You're right.  I'll get that stuff documented soon.

**Comment by rcrowley** [comment]
Released in v0.3.5.
