### ISSUE TITLE
SHA1Sum/SHA256Sum vs SHA1/SHA256 in Release file

### ISSUE THREAD

**Issue by antaflos** [rcrowley/freight#51]
It seems the Release file generated by Freight makes Debian (at least Wheezy) choke, because it labels the SHA1 and SHA256 checksums as "SHA1Sum" and "SHA256Sum" instead of "SHA1" and "SHA256".

This is the Release file for Squeeze: ftp://ftp.at.debian.org/debian/dists/squeeze/Release Note how it says "SHA1" and "SHA256" instead of "SHA1Sum" and "SHA256Sum". Same for Ubuntu Trusty: ftp://at.archive.ubuntu.com/ubuntu/dists/trusty/Release

Is there a reason Freight uses these labels instead of the "official" ones?

As far as I can see the fix for this should be quite trivial, around line 177 in /usr/lib/freight/apt.sh.

**Comment by rcrowley** [comment]
Thanks, @antaflos!
