### ISSUE TITLE
freight-{add,cache} should complain on invalid .deb files

### ISSUE THREAD

**Issue by tmm1** [rcrowley/freight#7]
Something like this should be enough to detect valid files, but I'm not sure how to hook it up to `freight-add`. It should probably go into `freight-cache` as well, in case you end up with an invalid file in `/var/lib/freight`.

``` sh
# Verify given file is a valid debian package.
apt_verify() {
    ar p "$1" control.tar.gz || {
        echo "# [freight] "$1" is not a valid debian package" >&2
        exit 1
    }
}
```

**Comment by tmm1** [comment]
Actually, you can just use `dpkg-deb`:

```
$ dpkg-deb -I random
dpkg-deb: `random' is not a debian format archive
```

**Comment by rcrowley** [comment]
28aa9299d80ae2766ecc5a32974369ee365c5f94 only handles invalid packages in `freight-cache`.  Do you think it's worth adding a new API `${MANAGER}_verify` that can be called from `freight-add`?  It's trivial to do so if it's important to you.

**Comment by tmm1** [comment]
Looks good. As long as it's in `freight-cache` I think that's fine. You can remove the offending file regardless of whether it was added via `freight-add` or put in the directory manually.
